Background #141d2b 
Foreground #14ffff 

Selection Background #5E35B1 
Cursor Color #E7C630 

Black #141d2b 
Bright Black #7B8097 

Red #F02C35 
Bright Red #FF0000 

Green #00FFB3 
Bright Green #f902e7 

Yellow #E7C630 
Bright Yellow #FFFC4C 

Blue #00FF00 
Bright Blue #F57800 

Cyan #14ffff 
Bright Cyan #A700FF 

Purple #123E7C
Bright Purple #CB1DCD

White #BDC3C7 
Bright White #C1DEFF 
