$active_window    = E7C630;
$inactive_window  = 141d2b;
$bg               = 141d2b;
$accent   		    = 14ffff; 
$button           = BDC3C7; 
$module           = BDC3C7; 
$button_active    = 14ffff;

$gray             = BDC3C7; 
$red              = F02C35; 
$green            = 00FF00;
$blue             = 14ffff;
$magenta          = ff3bf1;
$cyan             = 00FFB3;
$purple           = A700FF;
$yellow           = E7C630; 
$black            = 141d2b; 
$teal             = 00BFAE;

$active_window    = rgb(E7C630)
$inactive_window  = rgb(141d2b)
$bg               = rgb(141d2b)
$accent   		    = rgb(14ffff)
$button           = rgb(BDC3C7) 
$module           = rgb(BDC3C7) 
$button_active    = rgb(9fef00)

$gray             = rgb(BDC3C7); 
$red              = rgb(F02C35); 
$green            = rgb(00FF00);
$blue             = rgb(14ffff);
$magenta          = rgb(ff3bf1);
$cyan             = rgb(00FFB3);
$purple           = rgb(A700FF);
$yellow           = rgb(E7C630); 
$black            = rgb(141d2b); 
$teal             = rgb(00BFAE);


