$active_window    = d65d0e;
$inactive_window  = 928374; 
$bg               = 1d2021;
$accent   		    = d65d0e; 
$button           = 665c54; 
$module           = 7c6f64; 
$button_active    = a89984;

$red              = cc241d; 
$green            = 98971a;
$blue             = 458588;
$purple           = b16286;
$yellow           = d79921;
$aqua             = 689d6a;
$orange           = d65d0e;
$gray             = 928374; 


$active_window    = rgb(d65d0e)
$inactive_window  = rgb(928374) 
$bg               = rgb(1d2021)
$accent   		    = rgb(d65d0e)
$button           = rgb(665c54) 
$module           = rgb(7c6f64) 
$button_active    = rgb(a89984)

$red              = rgb(cc241d) 
$green            = rgb(98971a)
$blue             = rgb(458588)
$purple           = rgb(b16286)
$yellow           = rgb(d79921)
$aqua             = rgb(689d6a)
$orange           = rgb(d65d0e)
$gray             = rgb(928374) 

