preload = /home/oshitaka/Pictures/20-wallpapers/25-summer/edgar-chaparro-VjZwxRFLB_M-unsplash.jpg
preload = /home/oshitaka/Pictures/20-wallpapers/25-summer/edgar-chaparro-VjZwxRFLB_M-unsplash.jpg
wallpaper = HDMI-A-1, /home/oshitaka/Pictures/20-wallpapers/25-summer/edgar-chaparro-VjZwxRFLB_M-unsplash.jpg
wallpaper = eDP-1, /home/oshitaka/Pictures/20-wallpapers/25-summer/edgar-chaparro-VjZwxRFLB_M-unsplash.jpg

IPC = on

splash = false


