preload = /home/oshitaka/Pictures/20-wallpapers/27-art/wallpaperflare.com_wallpaper(18).jpg
wallpaper = HDMI-A-1, /home/oshitaka/Pictures/20-wallpapers/27-art/wallpaperflare.com_wallpaper(18).jpg
wallpaper = eDP-1, /home/oshitaka/Pictures/20-wallpapers/27-art/wallpaperflare.com_wallpaper(18).jpg

IPC = on

splash = false


