preload = /home/oshitaka/Pictures/20-wallpapers/27-art/1281520.jpg
wallpaper = HDMI-A-1, /home/oshitaka/Pictures/20-wallpapers/27-art/1281520.jpg
wallpaper = eDP-1, /home/oshitaka/Pictures/20-wallpapers/27-art/1281520.jpg

IPC = on

splash = false


